name: 'Create or Update Project Card'
description: 'A GitHub action to create or update a project card'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT'
    default: ${{ github.token }}
  project-owner:
    description: >
      The owner of the project. Either an organization, or user.
    default: ${{ github.repository_owner }}
  project-number:
    description: >
      The number of the project.
      Semi-required. Either `project-number` OR `project-title` must be supplied.
  project-title:
    description: >
      The title of the project.
      Semi-required. Either `project-number` OR `project-title` must be supplied.
      Note that a project's title is not unique. The action will use the first matching project found.
  column-name:
    description: 'The name of the column to add a card to, or move an existing card to.'
    required: true
  repository:
    description: 'The GitHub repository containing the issue or pull request.'
    default: ${{ github.repository }}
  issue-number:
    description: 'The issue or pull request number to associate with the card.'
    default: ${{ github.event.issue.number }}
outputs:
  card-id:
    description: 'The ID of the card.'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'file-plus'
  color: 'gray-dark'
